version: "3"

services:
  app:
    build:
      context: ./dockerfiles
      # dockerfile: ubuntu-focal-mysql.dockerfile
      dockerfile: ubuntu-jammy-mariadb.dockerfile
    privileged: true
    command:
      - "/sbin/init"
