# NOTE: ip_addressに登録するサーバには事前にisuconユーザでsshできるようにしておく

test:
  hostname:   isucon11-test
  ip_address: 18.183.127.238

host01:
  hostname:   isucon9-qualify-01
  ip_address: 13.114.34.238
host02:
  hostname:   isucon9-qualify-02
  ip_address: 54.199.171.172

#host01:
#  hostname:   isucon11-qualify-01
#  ip_address:
#host02:
#  hostname:   isucon11-qualify-02
#  ip_address:
#host03:
#  hostname:   isucon11-qualify-03
#  ip_address:
