# NOTE: ip_addressに登録するサーバには事前にisuconユーザでsshできるようにしておく

#test:
#  hostname:   isucon11-test
#  ip_address: 18.183.127.238

host01:
  hostname:   isucon10-qualify-01
  ip_address: 18.182.47.135
host02:
  hostname:   isucon10-qualify-02
  ip_address: 13.115.56.212
host03:
  hostname:   isucon10-qualify-03
  ip_address: 18.183.34.129
