# NOTE: ip_addressに登録するサーバには事前にisuconユーザでsshできるようにしておく

#test:
#  hostname:   isucon11-test
#  ip_address:

host01:
  hostname:   isucon11-qualify-01
  ip_address: 18.181.130.91
host02:
  hostname:   isucon11-qualify-02
  ip_address: 54.249.131.215
host03:
  hostname:   isucon11-qualify-03
  ip_address: 52.194.98.165
