# NOTE: ip_addressに登録するサーバには事前にisuconユーザでsshできるようにしておく

#test:
#  hostname:   isucon11-test
#  ip_address:

host01:
  hostname:   isucon11-qualify-01
  ip_address: xxx.xxx.xxx.xxx
host02:
  hostname:   isucon11-qualify-02
  ip_address: xxx.xxx.xxx.xxx
host03:
  hostname:   isucon11-qualify-03
  ip_address: xxx.xxx.xxx.xxx
