name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/dependabot.yml"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
      - ".github/dependabot.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        dockerfile:
          - ubuntu-focal-mysql
          - ubuntu-focal-mariadb
          - ubuntu-jammy-mysql
          - ubuntu-jammy-mariadb

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      # c.f. https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/${{ matrix.dockerfile }}.dockerfile
          push: false
          tags: isucon-itamae:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: docker images

      - run: docker run --privileged -d --name isucon-itamae_app_1 isucon-itamae:latest /sbin/init

      - run: bundle exec rake test:itamae
        env:
          LOG_LEVEL: info

      - run: bundle exec rake test:clean
        if: always()

      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "! success()"
        continue-on-error: true
        with:
          job_name: ${{ format('*build* ({0})', matrix.dockerfile) }}
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: lazy-actions/slatify@master
        if: always()
        continue-on-error: true
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
